---

- name: ensure path /etc/docker was created
  file:
    path: /etc/docker
    state: directory
    mode: 0755

- name: instalando dependencias - CentOS
  yum:
    name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2']
    state: present
    update_cache: true

- name: add repo docker - CentOS
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: 0440

- name: instalando docker - CentOS
  yum:
    name: docker-ce-18.06.2.ce
    state: present
    update_cache: true

- name: adicionando os parametros de confiugração do docker daemon - CentOS
  blockinfile:
    dest: /etc/docker/daemon.json
    marker: ''
    create: true
    block: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2",
        "storage-opts": [
          "overlay2.override_kernel_check=true"
        ]
      }
      
- name: disabilita SELinux - CentOS
  command: setenforce 

- name: disabilita SELinux on reboot - CentOS
  selinux:
    state: disabled

- name: add repositorio YUM Kubernetes - CentOS
  yum_repository:
    name: Kubernetes
    description: Kubernetes YUM repository
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: true