---

- name: ensure path /etc/docker was created
  file:
    path: /etc/docker
    state: directory
    mode: 0755

- name: instalando dependencias - Ubuntu
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
    update_cache: true

- name: adicionando chave gpg do docker - Ubuntu
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: adicionando o repo do docker - Ubuntu
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present
    filename: docker-ce
     
- name: instalando o docker ce - Ubuntu
  apt:
    name: docker-ce=18.06.2~ce~3-0~ubuntu
    update_cache: true
    state: present

- name: adicionando o arquivo daemon.json - Ubuntu
  blockinfile:
    dest: /etc/docker/daemon.json
    create: yes
    block: |
       {
         "exec-opts": ["native.cgroupdriver=systemd"],
         "log-driver": "json-file",
         "log-opts": {
           "max-size": "100m"
         },
         "storage-driver": "overlay2"
       }

- name: adicionando a chave do repo - Ubuntu
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: adicionando o repo do kubernete - Ubuntu
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes